-- MySQL Script generated by MySQL Workbench
-- Fri Mar 17 18:46:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8 ;
USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`address_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`address_customer` (
  `idaddress` INT(11) NOT NULL AUTO_INCREMENT,
  `address_street` VARCHAR(60) NOT NULL,
  `address_postcode` INT(11) NOT NULL,
  `address_number` INT(11) NOT NULL,
  `address_city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaddress`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`address_supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`address_supplier` (
  `idaddress` INT(11) NOT NULL AUTO_INCREMENT,
  `address_street` VARCHAR(60) NOT NULL,
  `address_postcode` INT(11) NOT NULL,
  `address_number` INT(11) NOT NULL,
  `address_city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaddress`))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`customers` (
  `idcustomers` INT(11) NOT NULL AUTO_INCREMENT,
  `customers_name` VARCHAR(45) NOT NULL,
  `customers_phone_number` INT(11) NOT NULL,
  `customers_mail` VARCHAR(120) NULL DEFAULT NULL,
  `customers_record_date` DATE NOT NULL,
  `customers_recommendation` VARCHAR(45) NULL DEFAULT NULL,
  `address_customer_idaddress` INT(11) NOT NULL,
  PRIMARY KEY (`idcustomers`),
  INDEX `fk_customers_address_customer1_idx` (`address_customer_idaddress` ASC),
  CONSTRAINT `fk_customers_address_customer1`
    FOREIGN KEY (`address_customer_idaddress`)
    REFERENCES `optica`.`address_customer` (`idaddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`supplier` (
  `supplier_id` INT(11) NOT NULL AUTO_INCREMENT,
  `supplier_name` VARCHAR(45) NOT NULL,
  `supplier_phone_number` INT(11) NOT NULL,
  `supplier_fax_number` INT(11) NULL DEFAULT NULL,
  `supplier_nif` VARCHAR(9) NOT NULL,
  `address_supplier_idaddress` INT(11) NOT NULL,
  PRIMARY KEY (`supplier_id`),
  INDEX `fk_supplier_address_supplier1_idx` (`address_supplier_idaddress` ASC),
  CONSTRAINT `fk_supplier_address_supplier1`
    FOREIGN KEY (`address_supplier_idaddress`)
    REFERENCES `optica`.`address_supplier` (`idaddress`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`sale` (
  `sale_id` INT(11) NOT NULL AUTO_INCREMENT,
  `sale_seller_name` VARCHAR(45) NOT NULL,
  `sale_date` DATE NOT NULL,
  `customers_idcustomers` INT(11) NOT NULL,
  PRIMARY KEY (`sale_id`),
  INDEX `fk_sale_customers1_idx` (`customers_idcustomers` ASC),
  CONSTRAINT `fk_sale_customers1`
    FOREIGN KEY (`customers_idcustomers`)
    REFERENCES `optica`.`customers` (`idcustomers`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `optica`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`glasses` (
  `glasses_id` INT(11) NOT NULL AUTO_INCREMENT,
  `glasses_brand` VARCHAR(45) NOT NULL,
  `glasses_graduation_left_eye` DOUBLE NOT NULL,
  `glasses_graduation_right_eye` DOUBLE NOT NULL,
  `glasses_frame_type` VARCHAR(45) NOT NULL,
  `glasses_frame_color` VARCHAR(45) NOT NULL,
  `glasses_lenses_color` VARCHAR(45) NOT NULL,
  `glasses_price` INT(11) NOT NULL,
  `supplier_supplier_id` INT(11) NOT NULL,
  `sale_sale_id` INT(11) NOT NULL,
  PRIMARY KEY (`glasses_id`),
  INDEX `fk_glasses_supplier_idx` (`supplier_supplier_id` ASC),
  INDEX `fk_glasses_sale1_idx` (`sale_sale_id` ASC),
  CONSTRAINT `fk_glasses_supplier`
    FOREIGN KEY (`supplier_supplier_id`)
    REFERENCES `optica`.`supplier` (`supplier_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_glasses_sale1`
    FOREIGN KEY (`sale_sale_id`)
    REFERENCES `optica`.`sale` (`sale_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
